name: jenkins_docker

services:
  jenkins:
    build:
      context: ./
    restart: always
    volumes:
      - ./jenkins_volume:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

    networks:
      - networkdocker

networks:
  networkdocker:
    driver: bridge
  


